### ISSUE TITLE
Unable to resolve any data file after loading once

### ISSUE THREAD

**Issue by Fischer-love-fish** [huggingface/datasets#3431]
when I rerun my program, it occurs this error
" Unable to resolve any data file that matches '['**train*']' at /data2/whr/lzy/open_domain_data/retrieval/wiki_dpr with any supported extension ['csv', 'tsv', 'json', 'jsonl', 'parquet', 'txt', 'zip']", so how could i deal with this problem?
thx.
And below is my code .
![image](https://user-images.githubusercontent.com/84694183/146023446-d75fdec8-65c1-484f-80d8-6c20ff5e994b.png)

**Comment by lhoestq** [comment]
Hi ! `load_dataset` accepts as input either a local dataset directory or a dataset name from the Hugging Face Hub.

So here you are getting this error the second time because it tries to load the local `wiki_dpr` directory, instead of `wiki_dpr` from the Hub. It doesn't work since it's a **cache** directory, not a **dataset** directory in itself.

To fix that you can use another cache directory like `cache_dir="/data2/whr/lzy/open_domain_data/retrieval/cache"`

**Comment by Fischer-love-fish** [comment]
thx a lot

**Comment by Arij-Aladel** [comment]
Hello my question is simple but at the same time I can not understand the reason of the error
In short I am trying

[this script](https://github.com/huggingface/transformers/blob/v4.24.0/examples/pytorch/summarization/run_summarization_no_trainer.py)

The datasets that can be used are listed down in [this line](https://github.com/huggingface/transformers/blob/94b3f544a1f5e04b78d87a2ae32a7ac252e22e31/examples/pytorch/summarization/run_summarization_no_trainer.py#L78)

very simple whenever I use any data set except cnn_daily(for example xsum) I got this error

EmptyDatasetError: The directory at xsum doesn’t contain any data files

why?
