### ISSUE TITLE
set_format("np") no longer works for Image data

### ISSUE THREAD

**Issue by cgarciae** [huggingface/datasets#3553]
## Describe the bug
`dataset.set_format("np")` no longer works for image data, previously you could load the MNIST like this:

```python
dataset = load_dataset("mnist")
dataset.set_format("np")
X_train = dataset["train"]["image"][..., None] # <== No longer a numpy array
```
but now it doesn't work, `set_format("np")` seems to have no effect and the dataset just returns a list/array of PIL images instead of numpy arrays as requested.

**Comment by cgarciae** [comment]
A quick fix for now is doing this:

```python
X_train = np.stack(dataset["train"]["image"])[..., None]

**Comment by andreaferretti** [comment]
This error also propagates to jax

**Comment by mariosasko** [comment]
Hi! We've recently introduced a new Image feature that yields PIL Images (and caches transforms on them) instead of arrays.

However, this feature requires a custom transform to yield np arrays directly:
```python
ddict = datasets.load_dataset("mnist")

def pil_image_to_array(batch):
     return {"image": [np.array(img) for img in batch["image"]]}  # or jnp.array(img) for Jax

ddict.set_transform(pil_image_to_array, columns="image", output_all_columns=True)
```
@albertvillanova @lhoestq WDYT? The Audio and the Image feature currently don't support the TF/Jax/PT Formatters, but for the Numpy Formatter maybe it makes more sense to return np arrays (and not a dict in the case of the Audio feature or a PIL Image object in the case of the Image feature).

**Comment by lhoestq** [comment]
Yes I agree it should return arrays and not a PIL image (and possible an array instead of a dict for audio data).
I'm currently finishing some code refactoring of the image and audio and opening a PR today. Maybe we can look into that after the refactoring

**Comment by mariosasko** [comment]
This has been fixed in https://github.com/huggingface/datasets/pull/5072, which is included in the latest release of `datasets`.
