### ISSUE TITLE
Add Biwi Kinect Head Pose Database

### ISSUE THREAD

**Issue by osanseviero** [huggingface/datasets#3822]
## Adding a Dataset
- **Name:** Biwi Kinect Head Pose Database
- **Description:** Over 15K images of 20 people recorded with a Kinect while turning their heads around freely. For each frame, depth and rgb images are provided, together with ground in the form of the 3D location of the head and its rotation angles.
- **Data:** [*link to the Github repository or current dataset location*](https://icu.ee.ethz.ch/research/datsets.html)
- **Motivation:** Useful pose estimation dataset

Instructions to add a new dataset can be found [here](https://github.com/huggingface/datasets/blob/master/ADD_NEW_DATASET.md).

**Comment by dnaveenr** [comment]
Official dataset location : https://icu.ee.ethz.ch/research/datsets.html
In the "Biwi Kinect Head Pose Database" section, I do not find any information regarding "Downloading the dataset." . Do we mail the authors regarding this ?

I found the dataset on Kaggle : [Link](https://www.kaggle.com/kmader/biwi-kinect-head-pose-database) , but since 🤗 does not host any of the datasets, this would require the user to provide their Kaggle username and API key to download. 

Any inputs on how we could proceed ? Thank you.

**Comment by mariosasko** [comment]
Hi @dnaveenr! Thanks for tackling this issue. This link should work: https://data.vision.ee.ethz.ch/cvl/gfanelli/kinect_head_pose_db.tgz

**Comment by lhoestq** [comment]
Added in https://github.com/huggingface/datasets/pull/3903, thanks @dnaveenr !

**Comment by lhoestq** [comment]
It would be cool to find a copy of the data and host it directly in https://huggingface.co/datasets/ETHZurich/biwi_kinect_head_pose

**Comment by lhtht** [comment]
@lhoestq 

Hi, you mean I can download it by running python script in your link?

**Comment by lhoestq** [comment]
This dataset repository only contains a script that points to the URL of the file that doesn't exist anymore, so it's not usable anymore either :/

**Comment by lhoestq** [comment]
If we find a copy of the data we can upload the file in the dataset repository on HF, since the original data is not available anymore
