### ISSUE TITLE
datasets.set_progress_bar_enabled(False) not working in datasets v2

### ISSUE THREAD

**Issue by virilo** [huggingface/datasets#4085]
## Describe the bug

datasets.set_progress_bar_enabled(False) not working in datasets v2

## Steps to reproduce the bug
```python
datasets.set_progress_bar_enabled(False)
```

## Expected results
datasets not using any progress bar

## Actual results

AttributeError: module 'datasets' has no attribute 'set_progress_bar_enabled

## Environment info

datasets version 2

**Comment by virilo** [comment]
Now, I can't find any reference to set_progress_bar_enabled in the code.

I think it have been deleted

**Comment by albertvillanova** [comment]
Hi @virilo,

Please note that since `datasets` version 2.0.0, we have aligned with `transformers` the management of the progress bar (among other things):
- #3897

Now, you should update your code to use `datasets.logging.disable_progress_bar`.

You have more info in our docs: [Logging methods](https://huggingface.co/docs/datasets/package_reference/logging_methods)

**Comment by BigOneLiXiaoMing** [comment]
One important thing for beginner like me is: from datasets.utils.logging import disable_progress_bar
Do not forget the 'utils' or you will waste a long time like me....
