### ISSUE TITLE
Streaming not supported in Theivaprakasham/wildreceipt

### ISSUE THREAD

**Issue by NitishkKarra** [huggingface/datasets#4775]

**Comment by albertvillanova** [comment]
Thanks for reporting @NitishkKarra.

The root source of the issue is that streaming mode is not supported out-of-the-box for that dataset, because it contains a TAR file.

We have opened a discussion in the corresponding Hub dataset page, pointing out this issue: https://huggingface.co/datasets/Theivaprakasham/wildreceipt/discussions/1

I'm closing this issue here, so this discussion is transferred there instead.
