### ISSUE TITLE
Align task tags in dataset metadata

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#5137]
## Describe
Once we have agreed on a common naming for task tags for all open source projects, we should align on them.

## Steps
- [x] Align task tags in canonical datasets
  - [x] task_categories: 4 datasets
  - [x] task_ids (by @lhoestq)
- [x] Open PRs in community datasets
  - [x] task_categories: 451 datasets
  - [x] task_ids: 556 datasets

**Comment by lhoestq** [comment]
I removed all the invalid task_ids in datasts without namespace, based on the (internal) types.ts

**Comment by julien-c** [comment]
(Types.ts is not internal it's public)

**Comment by albertvillanova** [comment]
I have opened PRs to fix the task_ids in all datasets within a namespace as well.

**Comment by albertvillanova** [comment]
For future reference: this fix had some complications

When trying to open a PR to fix the task tags, ax exception was thrown if:
- the metadata contained "languages" or "licenses" (instead of "language" or "license")
- the metadata contained a non-valid language: `en-US` (instead of `en`), `no` (instead of `'no'`),...
- the metadata contained a non-valid license
- either `task_categories` or `task_ids` was not an array
- the metadata contained non-valid tag names

**Comment by albertvillanova** [comment]
All Hub datasets are done.

**Comment by julien-c** [comment]
great job! did you have feedback from Hub users/i.E. repo authors?

**Comment by dennlinger** [comment]
As someone with feedback on the updates (which I highly appreciate seeing included here :D), a few comments from a "user perspective":  

* I think the general confusion for me was also surrounding the hierarchy; it doesn't really become super clear (even when using the tagger space) that one is a subset of the other, especially since it seems to be still possible to include fine-grained tasks without the "parent category"?
* The datasets explorer still shows tags that are no longer valid (e.g., super specific ones such as `summarization-other-paper-abstract-generation`, but also ones that should be `task_categories`, such as `summarization`). I'm assuming this will be fixed soon, but until then it can confuse people who don't understand why they suddenly can't use seemingly still valid tags anymore.
* As I mentioned to @albertvillanova, having a dedicated page in the docs with explanations (especially wrt the difference between `task_categories` and `task_ids`) would be super helpful. However, I think it would have been sufficient to just include some description in the dataset PRs where you can link to the Github/other discussion on the topic :) That way, I can check myself what changes are expected to happen.

Thanks again for the streamlining process, I personally learned a fair bit about the tagging structure in the meantime!
Best,
Dennis

**Comment by julien-c** [comment]
Thanks to you both for your feedback! super useful! cc'ing @osanseviero too 🙂

> The datasets explorer still shows tags that are no longer valid

wait which explorer is that? is it https://huggingface.co/datasets/viewer/ ?

**Comment by dennlinger** [comment]
Sorry, this one: https://huggingface.co/datasets  
And then selecting the "Fine-Grained Tasks".

**Comment by julien-c** [comment]
good feedback! we'll improve this

**Comment by osanseviero** [comment]
Super useful feedback, thanks a lot!

**Comment by albertvillanova** [comment]
- Some people do not agree about current "hierarchy":
  - symbolic-regression: [yoshitomo-matsubara/srsd-feynman_hard](https://huggingface.co/datasets/yoshitomo-matsubara/srsd-feynman_hard/discussions/2#63614194c12a09b8a31457cc), [yoshitomo-matsubara/srsd-feynman_medium](https://huggingface.co/datasets/yoshitomo-matsubara/srsd-feynman_medium/discussions/2#6361418aeee0d27f04379e43), [yoshitomo-matsubara/srsd-feynman_easy](https://huggingface.co/datasets/yoshitomo-matsubara/srsd-feynman_easy/discussions/2#6361416e00905b1ffb8d0112)
    - Why don't we have symbolic-regression task?

**Comment by yoshitomo-matsubara** [comment]
@albertvillanova 
Thank you for sharing our voice here!

Yes, we want `symbolic-regression` to be listed as a task. This task has been attracting attention from the machine learning/deep learning community, and unfortunately existing symbolic regression datasets are de-centralized in the community (hosted at individual platforms like author website, github, etc).
It would be great for the community if Hugging Face can support the task.
