### ISSUE TITLE
wmt download speed example

### ISSUE THREAD

**Issue by sshleifer** [huggingface/datasets#525]
Continuing from the slack 1.0 roadmap thread w @lhoestq , I realized the slow downloads is only a thing sometimes. Here are a few examples, I suspect there are multiple issues. All commands were run from the same gcp us-central-1f machine.

```
import nlp
nlp.load_dataset('wmt16', 'de-en')
```
Downloads at 49.1 KB/S

Whereas 
```
pip install gdown # download from google drive
!gdown https://drive.google.com/uc?id=1iO7um-HWoNoRKDtw27YUSgyeubn9uXqj
```
Downloads at 127 MB/s. (The file is a copy of wmt-en-de raw).

```
nlp.load_dataset('wmt16', 'ro-en')
```
goes at 27 MB/s, much faster. 

if we wget the same data from s3 is the same download speed, but ¼ the file size:
```
wget https://s3.amazonaws.com/datasets.huggingface.co/translation/wmt_en_ro_packed_200_rand.tgz
```

Finally,
```
nlp.load_dataset('wmt19', 'zh-en')
```
Starts fast, but broken. (duplicate of #493 )

**Comment by lhoestq** [comment]
Thanks for creating the issue :)
The download link for wmt-en-de raw looks like a mirror. We should use that instead of the current url.
Is this mirror official ?

Also it looks like for `ro-en` it tried to download other languages. If we manage to only download the one that is asked it'd be cool

Also cc @patrickvonplaten

**Comment by sshleifer** [comment]
Mirror is not official.

**Comment by lhoestq** [comment]
Shall we host the files ourselves or it is fine to use this mirror in your opinion ?

**Comment by thomwolf** [comment]
Should we add an argument in `load_dataset` to replace some URL with another URL. This could also be used to use local files instead of the original files as requested by some users (e.g. when you made a dataset with the same format than SQuAD and what to use it instead of the official dataset files).

**Comment by sshleifer** [comment]
I think we should host it ourselves. I'll put the subset of wmt that we need on s3 and post a link over the weekend.

**Comment by Rachneet** [comment]
Is there a solution yet? The download speed is still too slow. 60-70kbps download for wmt16 and around 100kbps for wmt19.

**Comment by lhoestq** [comment]
I'm working on mirror links which will provide high download speed :)
See https://github.com/huggingface/datasets/issues/1892

**Comment by mariosasko** [comment]
Resolved via https://github.com/huggingface/datasets/pull/1912
