### ISSUE TITLE
Support fsspec 2023.10.0

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/datasets#6333]
Once root issue is fixed, remove temporary pin of fsspec < 2023.10.0 introduced by:
- #6331

Related to issue:
- #6330

As @ZachNagengast suggested, the issue might be related to:
- https://github.com/fsspec/filesystem_spec/pull/1381

**Comment by tomscholz** [comment]
Hi @albertvillanova @lhoestq 

I believe the pull request that pins the fsspec version (https://github.com/huggingface/datasets/pull/6331) was merged by mistake. Another fix for the issue was merged on the same day. See https://github.com/huggingface/datasets/pull/6334

I'm now having a issue in my project where I can't use newer versions of fsspec.

Can we remove the pin?

Have a nice day! :)

**Comment by albertvillanova** [comment]
Hi again, @tomscholz.

After a more cautious investigation, I think the pin is OK because there are other reasons for it. Chronologically:
- #6331 
- #6336 
- #6337 

The reason is that after version 2023.10.0, they changed again the behavior of their `glob` function. We are working on our side to support both previous and new glob behavior.

**Comment by albertvillanova** [comment]
Fixed by #6334 and #6336.
