### ISSUE TITLE
Downloaded datasets are not usable offline

### ISSUE THREAD

**Issue by ghazi-f** [huggingface/datasets#761]
I've been trying to use the IMDB dataset offline, but after downloading it and turning off the internet it still raises  an error from the ```requests``` library trying to reach for the online dataset.
Is this the intended behavior ?
(Sorry, I wrote the the first version of this issue while still on nlp 0.3.0).

**Comment by lhoestq** [comment]
Yes currently you need an internet connection because the lib tries to check for the etag of the dataset script online to see if you don't have it locally already.

If we add a way to store the etag/hash locally after the first download, it would allow users to first download the dataset with an internet connection, and still have it working without an internet connection.

I'll let you know when we add this feature.

**Comment by albertvillanova** [comment]
Already fixed by:
- #1726
